### ISSUE TITLE
help !

### ISSUE THREAD

**Issue by duchuAz** [TheFourGreatErrors/alpha-rptr#3]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.factory import BotFactory
  File "/root/ta-lib/alpha-rptr/src/__init__.py", line 252
    def notify(message: object, fileName: object = None) -> object:
                                ^
SyntaxError: invalid syntax

thx u !

**Comment by TheFourGreatErrors** [comment]
Hello, could you please tell me more about how to reproduce this error like what mode are you using, did you set your line api keys correctly, when exactly does it trigger this error?

**Comment by TheFourGreatErrors** [comment]
I suppose this is caused by older version of python, you should use 3.65 or newer.
