### ISSUE TITLE
Symbol not found: _TA_ACOS

### ISSUE THREAD

**Issue by balker0322** [TheFourGreatErrors/alpha-rptr#5]
need help. I'm having this error

lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so, 2): Symbol not found: _TA_ACOS

thanks

**Comment by TheFourGreatErrors** [comment]
Hello, this error seems to be related to TA-lib library, I would recommend you to try to create a virtual environment [https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/](url) and try installing everything according to instructions in the documentation in this repo and see what happens.
