### ISSUE TITLE
Bot has an error at start

### ISSUE THREAD

**Issue by marchapunkt** [TheFourGreatErrors/alpha-rptr#74]
File "/home/xxxxx/alpha-rptr/main.py", line 38, in <module>
    bot.run()
  File "/home/xxxxx/alpha-rptr/src/bot.py", line 275, in run
    self.exchange.show_result()
TypeError: Bybit.show_result() missing 1 required positional argument: 'plot

**Comment by TheFourGreatErrors** [comment]
Hi, I assume you are using the bybit-unified-stable branch, there was a redundant argument in `show_result()`. Feel free to try again and please let me know if everything works.
